name: cuuhoxe
version: 1.0.10+11
publish_to: none
description: App cuu ho xe
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  flutter_dotenv: ^5.0.0
  sentry_flutter: ^5.1.0
  firebase_core: ^1.3.0
  firebase_analytics: ^8.1.2
  firebase_messaging: ^10.0.3
  flutter_svg: ^0.22.0
  pull_to_refresh: ^2.0.0
  logger: ^1.0.0
  event_bus: ^2.0.0
  get_storage: ^2.0.2
  carousel_slider: ^4.0.0
  intl: ^0.17.0
  image_picker: ^0.8.1+3
  location: ^4.3.0
  geocode: ^1.0.1
  flutter_staggered_grid_view: ^0.4.0
  flutter_slidable: ^0.6.0
  cached_network_image: ^3.0.0
  google_maps_flutter: ^2.0.6
  adhara_socket_io: ^1.0.1+1
  url_launcher: ^6.0.9
  geocoding: ^2.0.0
  flutter_polyline_points: ^1.0.0
  get: ^4.3.4
  flutter_html: ^2.1.1
  flutter_rating_bar: ^4.0.0
  geolocator: ^7.4.0
  syncfusion_flutter_datepicker: ^19.2.51
  webview_flutter: ^2.0.12
  permission_handler: ^8.1.4+2
  app_settings: ^4.1.1
  package_info: ^2.0.2
  jiffy: ^4.1.0
  app_tracking_transparency: ^2.0.2+1
  contacts_service: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/gif/
    - assets/anim/
    - .env.dev
    - .env
